// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiEhhH3tpltOkb3Zn9W_Bvhf9qlmhpm8s',
    appId: '1:520548367958:web:23da18bddab42a7a6c85f7',
    messagingSenderId: '520548367958',
    projectId: 'mobplay-app',
    authDomain: 'mobplay-app.firebaseapp.com',
    storageBucket: 'mobplay-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJZf1aoyb3q3IvBvMAZLgHsK94g0Kqefs',
    appId: '1:520548367958:android:e25767b15a93ecdd6c85f7',
    messagingSenderId: '520548367958',
    projectId: 'mobplay-app',
    storageBucket: 'mobplay-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxUc5JJ7hHjvIVrqz_PFOmaIQWmeIkn-I',
    appId: '1:520548367958:ios:a9f65228fe917e0f6c85f7',
    messagingSenderId: '520548367958',
    projectId: 'mobplay-app',
    storageBucket: 'mobplay-app.firebasestorage.app',
    iosBundleId: 'com.example.mobplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxUc5JJ7hHjvIVrqz_PFOmaIQWmeIkn-I',
    appId: '1:520548367958:ios:a9f65228fe917e0f6c85f7',
    messagingSenderId: '520548367958',
    projectId: 'mobplay-app',
    storageBucket: 'mobplay-app.firebasestorage.app',
    iosBundleId: 'com.example.mobplay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiEhhH3tpltOkb3Zn9W_Bvhf9qlmhpm8s',
    appId: '1:520548367958:web:0dd449fadf3d5ebe6c85f7',
    messagingSenderId: '520548367958',
    projectId: 'mobplay-app',
    authDomain: 'mobplay-app.firebaseapp.com',
    storageBucket: 'mobplay-app.firebasestorage.app',
  );
}
